### ISSUE TITLE
/dev/tty: No such device or address

### ISSUE THREAD

**Issue by LEMMIIX** [denolehov/obsidian-git#227]
### Describe the bug

Win10, Obsidian 0.14.6, GitHub Desktop 3.0.0

I just started using Obsidian with Git today and I get multiple errors when trying to push:
```
git obsidian error: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No such file or directory
Pushing to https://github.com/LEMMIIX/myProject.git
```

Opening the console reveals more stuff I don't know how to interpret:
```
VM148:10614 Uncaught (in promise) Error: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No such file or directory
Pushing to https://github.com/LEMMIIX/myProject.git

    at Object.action (eval at <anonymous> (app.js:1:1), <anonymous>:10614:25)
    at PluginStore.exec (eval at <anonymous> (app.js:1:1), <anonymous>:10639:25)
    at eval (eval at <anonymous> (app.js:1:1), <anonymous>:8435:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (eval at <anonymous> (app.js:1:1), <anonymous>:8433:16)
    at GitExecutorChain.eval (eval at <anonymous> (app.js:1:1), <anonymous>:8417:44)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1:1), <anonymous>:7269:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Is there a §PATH I have to set, or a repo/directory I forgot to add?

### Steps to reproduce

_ _

### Operating system

Windows

### Plugin version

1.25.1

**Comment by LEMMIIX** [comment]
SOLVED - kind of?
Instead of using Obsidians function top push, I tried pushing via GitHub Desktop and it worked.
I still don't know how to fix the issues in Obsidian, but at least I found a work-around for now.

**Comment by Vinzent03** [comment]
Does [this](https://github.com/atom/atom/issues/8984#issuecomment-165722062) help?

**Comment by LEMMIIX** [comment]
> Does [this](https://github.com/atom/atom/issues/8984#issuecomment-165722062) help?

Not really, all it did is adding "Pushing to https://github.com/LEMMIIX/myProject.git" to the error message.

```
git obsidian error: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No such file or directory
Pushing to https://github.com/LEMMIIX/myProject.git

VM148:10620 Uncaught (in promise) Error: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No such file or directory
Pushing to https://github.com/LEMMIIX/myProject.git

    at Object.action (eval at <anonymous> (app.js:1:1), <anonymous>:10620:25)
    at PluginStore.exec (eval at <anonymous> (app.js:1:1), <anonymous>:10645:25)
    at eval (eval at <anonymous> (app.js:1:1), <anonymous>:8440:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (eval at <anonymous> (app.js:1:1), <anonymous>:8438:16)
    at GitExecutorChain.eval (eval at <anonymous> (app.js:1:1), <anonymous>:8422:44)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1:1), <anonymous>:7274:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Added the line you suggested to the config of the vault where the project is stored. Was that correct? Or is there a "global git config" I have to add this to?

**Comment by VincentUnfolded** [comment]
Hey, I had this same issue and after trying to fix it for like an hour and a half, what worked for me was downloading the git credential manager from this link, after that i tried to push from obsidian and logged in through my browser, hope this helps.
https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.877

**Comment by cmagin** [comment]
> Hey, I had this same issue and after trying to fix it for like an hour and a half, what worked for me was downloading the git credential manager from this link, after that i tried to push from obsidian and logged in through my browser, hope this helps.

Can confirm that installing GitCredentialManager solved this issue for me.
