### ISSUE TITLE
[Bug]: Obsidian git cannot run git command

### ISSUE THREAD

**Issue by Elmons** [denolehov/obsidian-git#470]
### Describe the bug

```
plugin:obsidian-git:25141 Error: spawnSync git ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_errnoException (node:internal/errors:595:12)
    at Object.spawnSync (node:internal/child_process:1111:20)
    at spawnSync (node:child_process:823:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:25137:57)
    at SimpleGit.setGitInstance (plugin:obsidian-git:24754:14)
    at ObsidianGit.init (plugin:obsidian-git:31955:31)
    at ObsidianGit.isAllInitialized (plugin:obsidian-git:32085:18)
    at ObsidianGit.commit (plugin:obsidian-git:32138:21)
    at Array.eval (plugin:obsidian-git:31651:60)
    at PromiseQueue.handleTask (plugin:obsidian-git:19215:20)
    at PromiseQueue.addTask (plugin:obsidian-git:19210:12)
    at Object.callback (plugin:obsidian-git:31651:41)
    at uR (app.js:1:1526336)
    at t.onChooseItem (app.js:1:1865376)
    at t.onChooseSuggestion (app.js:1:1753623)
    at t.selectSuggestion (app.js:1:1753173)
    at e.useSelectedItem (app.js:1:1562639)
    at Object.func (app.js:1:1561354)
    at e.handleKey (app.js:1:1054848)
    at e.onKeyEvent (app.js:1:1056104)
isGitInstalled @ plugin:obsidian-git:25141
setGitInstance @ plugin:obsidian-git:24754
init @ plugin:obsidian-git:31955
isAllInitialized @ plugin:obsidian-git:32085
commit @ plugin:obsidian-git:32138
eval @ plugin:obsidian-git:31651
handleTask @ plugin:obsidian-git:19215
addTask @ plugin:obsidian-git:19210
callback @ plugin:obsidian-git:31651
uR @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
（匿名） @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
plugin:obsidian-git:25141 Error: spawnSync git ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_errnoException (node:internal/errors:595:12)
    at Object.spawnSync (node:internal/child_process:1111:20)
    at spawnSync (node:child_process:823:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:25137:57)
    at SimpleGit.checkRequirements (plugin:obsidian-git:24994:15)
    at ObsidianGit.init (plugin:obsidian-git:31959:44)
    at async ObsidianGit.isAllInitialized (plugin:obsidian-git:32085:7)
    at async ObsidianGit.commit (plugin:obsidian-git:32138:10)
isGitInstalled @ plugin:obsidian-git:25141
checkRequirements @ plugin:obsidian-git:24994
init @ plugin:obsidian-git:31959
await in init（异步）
isAllInitialized @ plugin:obsidian-git:32085
commit @ plugin:obsidian-git:32138
eval @ plugin:obsidian-git:31651
handleTask @ plugin:obsidian-git:19215
addTask @ plugin:obsidian-git:19210
callback @ plugin:obsidian-git:31651
uR @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
（匿名） @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
plugin:obsidian-git:32633 git obsidian error: Cannot run git command
```

### Steps to reproduce

1.install git
2.install obsidian and obsidian git

### Expected Behavior

None

### Addition context

There is my configuration.
![image](https://user-images.githubusercontent.com/55799573/225825628-af5ad5bd-310a-413c-b52b-75a35b13c826.png)

![image](https://user-images.githubusercontent.com/55799573/225825564-bf504650-073f-4c31-8945-cb8ea228ae83.png)

And i can use git bash to add,commit and push.

### Operating system

Windows

### Installation Method

None

### Plugin version

2.17.4

**Comment by Vinzent03** [comment]
May you update your git installation to ensure you have 3rd-party software enabled? You can find an image [here](https://publish.obsidian.md/git-doc/Installation)

**Comment by Elmons** [comment]
> 

I ensure that 3rd-party software has been enabled.

**Comment by Vinzent03** [comment]
Can you run `git --version` in the default command line. So don't use git bash, but the command line (cmd)?

**Comment by Elmons** [comment]
> Can you run `git --version` in the default command line. So don't use git bash, but the command line (cmd)?

Yes,thiere is the image.
![image](https://user-images.githubusercontent.com/55799573/225879705-d20ef53e-86e8-4532-8b9c-b56fecabffd5.png)
I am thinking that is the computer settings or not?Because it's a school computer.I don't know if it's a clearance issue。

**Comment by Elmons** [comment]
But I can use git bash or cmd to push my repo.  So i think that is not a permissional issue.

**Comment by Elmons** [comment]
> May you run `where git` in cmd and set the output as "Custom git binary path" setting? Then restart Obsidian and see if the plugin can now find git.

Wow!Thanks!The issue was settled!
